import { Command } from '@commander-js/extra-typings'
import { glob } from 'fs/promises'
import { complete } from '../lib/aiclient'
import { settings } from '../lib/settings'
import tui from '../lib/tui'
import { projectDir, readTextInDir } from '../lib/utils'
import { join } from 'path'
import { all } from 'radash'
import { getLoggedInJutgeClient } from '../lib/login'

export const askCmd = new Command('ask')
    .description('Ask questions about jutge-toolkit to JutgeAI')

    .argument('[question]', 'your question about the toolkit')
    .option('-m, --model <model>', 'AI model to use', settings.defaultModel)

    .action(async (question, { model }) => {
        const jutge = await getLoggedInJutgeClient()
        const systemPrompt = await readTextInDir(join(projectDir(), 'assets', 'prompts', 'ask'), 'ask.md')

        const docs = await loadDocumentation() // Load your markdown files
        const fullPrompt = `${docs}\n\nUser question: ${question}`

        const answer = await complete(jutge, model, systemPrompt, fullPrompt)
        await tui.markdown(answer)
        tui.warning(
            `This answer generated by JutgeAI using ${model} is not authoritative but we hope it will help you.`,
        )
    })

export async function loadDocumentation(): Promise<string> {
    const documentsDir = join(projectDir(), 'docs')
    const toolkitDir = join(projectDir(), 'toolkit')

    const documentPaths = await Array.fromAsync(glob('*.{md,tex}', { cwd: documentsDir }))
    const sourcePaths = await Array.fromAsync(glob('*.ts', { cwd: toolkitDir }))

    const documents = await all(documentPaths.map((file) => readTextInDir(documentsDir, file)))
    const sources = await all(sourcePaths.map((file) => readTextInDir(toolkitDir, file)))

    const texts = [...documents, ...sources]

    return texts.join('\n\n')
}
