#!/usr/bin/env bash

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo "This script installs the latest version of jutge-vinga."
    exit 0
fi

sudo wget -O /usr/local/bin/jutge-vinga https://github.com/jutge-org/jutge-vinga-bin/raw/master/jutge-vinga-linux

sudo chown root:root /usr/local/bin/jutge-vinga
sudo chmod 700 /usr/local/bin/jutge-vinga
sudo chmod u+s /usr/local/bin/jutge-vinga

ls -la /usr/local/bin/jutge-vinga

echo "worker ALL=(ALL) NOPASSWD: /usr/local/bin/jutge-vinga" | (sudo su -c 'EDITOR="tee -a" visudo -f /etc/sudoers.d/`whoami`')
